version: '3'

services:
  app:
    image: jboss/keycloak:15.0.0
    environment:
      - KEYCLOACK_USER=admin
      - KEYCLOACK_PASSWORD=admin
      - DB_VENDOR=h2
    volumes:
      - ./realm-export.json:/tmp/realm-export.json
    ports:
      - 7025:7025
